### ISSUE TITLE
Fails on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [alexandru-elisei/moodle-tool_downloaddata#1]
Attempting to download users on PostgreSQL, this fails on line 81 of index_users.php. Because of the way how the exception is swallowed there, it is hard to get any debugging info (why do you catch the exception just to throw another one will less details?) Anyway I managed to debug it to the following, which is typical MySQL-ism error:

```
Debug info: ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 12: ORDER BY u.lastname, u.firstname, u.id
^
SELECT DISTINCT username,firstname,lastname,email,auth, ra.roleid
FROM mdl_role_assignments ra
JOIN mdl_user u ON u.id = ra.userid
JOIN mdl_role r ON ra.roleid = r.id

LEFT JOIN mdl_role_names rn ON (rn.contextid = $1 AND rn.roleid = r.id)

WHERE (ra.contextid = $2 )
AND ra.roleid = $3


ORDER BY u.lastname, u.firstname, u.id
[array (
0 => 34,
1 => 34,
2 => '4',
)]
Error code: dmlreadexception
Stack trace:

    line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 4238 of /lib/accesslib.php: call to pgsql_native_moodle_database->get_records_sql()
    line 490 of /admin/tool/downloaddata/classes/processor.php: call to get_role_users()
    line 222 of /admin/tool/downloaddata/classes/processor.php: call to tool_downloaddata_processor->get_users()
    line 78 of /admin/tool/downloaddata/index_users.php: call to tool_downloaddata_processor->prepare()
```

**Comment by alexandru-elisei** [comment]
As far as I can tell this error is a bug with the Moodle code, I have created an issue describing the problem: https://tracker.moodle.org/browse/MDL-52574. I am using only the Moodle database wrapper functions, which should mean that the code is database agnostic.

I added a workaround for the error in commit cd3af37914dd5d657aca58a37767cb073c111f2b which will be integrated in the stable branches as soon as the Moodle issue is confirmed.

As for your comment about the way I handle the exceptions on the web pages. I assumed that the only exceptions that will be raised will be user errors (like requesting non-existing fields), so I thought that a one line message describing the error will be enough. Evidently, I was wrong. I reworked all the exception wrappers from the web pages.
