### ISSUE TITLE
Missing default values and more userful help for the "Fields" field

### ISSUE THREAD

**Issue by mudrd8mz** [alexandru-elisei/moodle-tool_downloaddata#2]
When downloading users, the "Fields" field is empty. The user (admin) has to know details about the database table names to know what to list here. It might help a bit if the default value was something reasonable (such as lastname, firstname, email) and the help popup contained more examples of useful fields.

Additionally, the help currently reads "Overrides default fields". However, I have not found a way how these _default fields_ can be defined?

**Comment by mudrd8mz** [comment]
Ok, I found something related to defaults in the help popup "Use the default values from DOWNLOADDATA_PLUGIN_DIRECTORY/config.php."

From user perspective, this does not really say much. Why are not default values configured via the plugin settings form?

**Comment by alexandru-elisei** [comment]
I chose to use the config.php file for configuration because it ties in better with the cli script, which I find faster and more convenient to use.

But you have a fair point, I will try to find a way to make these settings more explicit, thank you for the suggestion.

**Comment by alexandru-elisei** [comment]
Released version 3.0.3 with (what I hope to be) more helpful help messages as a quick fix for the issue.

**Comment by alexandru-elisei** [comment]
Added multi-select elements for roles and fields, so there will be no ambiguity regarding what fields to download. I will close the issue after I release the next version, the changes are only on master right now.

**Comment by alexandru-elisei** [comment]
Released the new version, closing.
