### ISSUE TITLE
Ability to include category name / name-path in the course list export

### ISSUE THREAD

**Issue by mudrd8mz** [alexandru-elisei/moodle-tool_downloaddata#3]
A virtual field like "categoryname" or so could be supported.

**Comment by alexandru-elisei** [comment]
Added multi-select elements for roles and fields, so there will be no ambiguity regarding what fields to download. I will close the issue after I release the next version, the changes are only on master right now.

**Comment by alexandru-elisei** [comment]
Released the new version, closing.
